language = "typescript"
version = "1.0.13"
compiled = false
extension = "ts"
environment = ["PATH=/opt/bun/1.0.13"]
build_command = []
run_command = ["/opt/bun/1.0.13/bun", "{file}"]
test_file = "test.ts"
aliases = ["typescript", "ts"]
should_limit_memory = false
memory_limit = 1024
process_limit = 2048
allowed_entrypoints = 1
