import ThemeLayout from '@/components/layouts/ThemeLayout';
import LoadingSpinner from '@/components/ui/spinner/loading-spinner';
import nohemi from '@/lib/fonts/nohemi';

import '@/styles/global.css';
import type { Metadata } from 'next';
import dynamic from 'next/dynamic';

const MainLayout = dynamic(() => import('@/components/layouts/MainLayout'), {
  loading: () => <LoadingSpinner />,
  ssr: false,
});

export const metadata: Metadata = {
  title: 'Carai',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nohemi.className}>
        <ThemeLayout>
          <MainLayout>{children}</MainLayout>
        </ThemeLayout>
      </body>
    </html>
  );
}
