services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: $APP__DATABASE__USERNAME
      POSTGRES_PASSWORD: $APP__DATABASE__PASSWORD
      POSTGRES_DB: $APP__DATABASE__NAME
    ports:
      - target: $APP__DATABASE__PORT
        published: $APP__DATABASE__PORT
        protocol: tcp
        mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: $APP__PGADMIN__EMAIL
      PGADMIN_DEFAULT_PASSWORD: $APP__PGADMIN__PASSWORD
    ports:
      - target: $APP__PGADMIN__PORT
        published: $APP__PGADMIN__PORT
        protocol: tcp
        mode: host
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
