services:
  db:
    image: postgres:13.16-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: $APP__DATABASE__USERNAME
      POSTGRES_PASSWORD: $APP__DATABASE__PASSWORD
      POSTGRES_DB: $APP__DATABASE__NAME
    ports:
      - target: $APP__DATABASE__PORT
        published: $APP__DATABASE__PORT
        protocol: tcp
        mode: host

  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - target: $APP__REDIS__PORT
        published: $APP__REDIS__PORT
        protocol: tcp
        mode: host
