services:
  db:
    image: postgres:13.16-bookworm
    container_name: postgres
    environment:
      POSTGRES_USER: $APP__DATABASE_USERNAME
      POSTGRES_PASSWORD: $APP__DATABASE_PASSWORD
      POSTGRES_DB: $APP__DATABASE_NAME
    ports:
      - target: $APP__DATABASE_PORT
        published: $APP__DATABASE_PORT
        protocol: tcp
        mode: host

  redis:
    image: redis:bookworm
    container_name: redis
    ports:
      - target: $APP__REDIS_PORT
        published: $APP__REDIS_PORT
        protocol: tcp
        mode: host
