export type SiteConfig = typeof siteConfig

const siteConfig = {
    name: 'Carai',
    type: 'website',
    title: 'Carai - Code Playground',
    author: 'Success Kingsley <hello@xosnrdev.tech>',
    description:
        'A web application that makes coding simple and accessible. Write, test, and share code snippets in multiple programming languages directly from your browser',
    language: 'en',
    OGImage: '/carai-og.png',
    email: 'hello@xosnrdev.tech',
    links: {
        url: 'https://codespacex.com',
        repo: 'https://github.com/xosnrdev/carai',
        github: 'https://github.com/xosnrdev',
        twitter: 'https://twitter.com/xosnrdev',
        authorUrl: 'https://xosnrdev.tech',
    },
    twitterHandle: '@xosnrdev',
    locale: 'en_US',
    keywords: [
        'code online',
        'online code playground',
        'online code editor',
        'online code playground',
        'online coding sandbox',
        'online code compiler',
        'online code runner',
        'online code interpreter',
        'online code debugger',
        'online remote code execution',
        'carai',
        'carai sandbox',
        'carai code editor',
        'carai code playground',
        'carai code compiler',
        'carai code runner',
        'carai code interpreter',
        'carai code debugger',
        'carai online code editor',
        'carai online code playground',
        'carai online code compiler',
        'carai online code runner',
        'carai online code interpreter',
        'carai online code debugger',
    ],
    categories: [
        'Programming',
        'Code Editor',
        'Online Tools',
        'Software Development',
        'Technology',
        'Education',
        'Learning Tools',
        'Developer Tools',
        'Open Source',
        'Algorithm',
        'Computer Science',
        'Coding',
        'Programming',
    ],
    publisher: 'Success Kingsley <hello@xosnrdev.tech>',
}

export default siteConfig
