export type SiteConfig = typeof siteConfig

const siteConfig = {
    name: 'Carai',
    type: 'website',
    title: 'Carai - Code Playground',
    author: 'Success Kingsley',
    description: 'Carai: Your online coding playground.',
    language: 'en-US',
    themeColor: {
        dark: '#2f2f3a',
        light: '#f1f5f9',
    },
    links: {
        url: 'https://cexaengine.com',
        repo: 'https://github.com/xosnrdev/carai',
        logo: '/carai-icon.svg',
        OGImage: '/carai-og.png',
        email: 'successxodev@gmail.com',
        github: 'https://github.com/xosnrdev',
        twitter: 'https://twitter.com/xosnrdev',
        authorUrl: 'https://xosnrdev.tech',
    },
    twitterHandle: '@xosnrdev',
    locale: 'en-US',
    keywords: [
        'code online',
        'code playground',
        'online code editor',
        'online code playground',
        'coding sandbox',
        'online code sandbox',
        'online code compiler',
        'online code runner',
        'online code interpreter',
        'online code debugger',
        'sandbox code editor',
        'sandbox code playground',
        'sandbox code compiler',
        'sandbox code runner',
        'sandbox code interpreter',
        'sandbox code debugger',
        'remote code execution',
        'online remote code execution',
        'carai',
        'carai sandbox',
        'carai code editor',
        'carai code playground',
        'carai code compiler',
        'carai code runner',
        'carai code interpreter',
        'carai code debugger',
        'carai online code editor',
        'carai online code playground',
        'carai online code compiler',
        'carai online code runner',
        'carai online code interpreter',
        'carai online code debugger',
    ],
    categories: [
        'Programming',
        'Code Editor',
        'Online Tools',
        'Software Development',
        'Technology',
        'Education',
        'Learning Tools',
        'Developer Tools',
        'Open Source',
        'Algorithm',
        'Computer Science',
        'Coding',
        'Programming',
    ],
    publisher: 'Carai Team',
}

export default siteConfig
