export type SiteConfig = typeof siteConfig

const siteConfig = {
    name: 'Carai',
    type: 'website',
    title: 'Carai - Write, Test, and Share Code Online',
    author: 'Success Kingsley',
    description:
        'An online platform to easily write, test, and share code with others at the speed of thought. Carai is your all-in-one open-source platform for coding, testing, and collaboration.',
    language: 'en',
    OGImage: '/carai-og.png',
    favicon: '/favicon.ico',
    email: 'hello@xosnrdev.tech',
    socials: {
        repo: 'https://github.com/xosnrdev/carai',
        github: 'https://github.com/xosnrdev',
        twitter: 'https://twitter.com/xosnrdev',
        authorUrl: 'https://xosnrdev.tech',
    },
    twitterHandle: '@xosnrdev',
    locale: 'en_US',
    siteUrl: 'https://codespacex.com',
    keywords: [
        'online code editor',
        'code sharing platform',
        'collaborative coding',
        'code testing tool',
        'online programming environment',
        'code playground',
        'real-time code execution',
        'multi-language code editor',
        'code snippet sharing',
        'interactive coding platform',
        'online compiler',
        'code collaboration tool',
        'remote pair programming',
        'code review platform',
        'live code sharing',
        'instant code execution',
        'web-based IDE',
        'coding practice platform',
        'programming learning tool',
        'code debugging online',
        'carai',
        'carai code editor',
        'carai code sharing',
        'carai code testing',
    ],
    categories: [
        'Online Code Editor',
        'Code Sharing Platform',
        'Programming Tools',
        'Developer Collaboration',
        'Software Development',
        'Educational Technology',
        'Coding Practice',
        'Web-based IDE',
        'Code Testing',
        'Programming Learning',
        'Code Execution Platform',
        'Open Source Tools',
    ],
    publisher: 'Success Kingsley',
}

export default siteConfig
