# name: Publish to Cloudflare Pages

# on:
#   push:
#     branches:
#       - master # Deploy when there's a push to the main branch

# permissions:
#   contents: read
#   deployments: write
#   statuses: write

# env:
#   SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#   SENTRY_DSN: ${{ secrets.EDITOR_SENTRY_DSN }}

# jobs:
#   publish:
#     name: Publish to Cloudflare Pages
#     runs-on: ubuntu-latest
#     container: node:20.12
#     defaults:
#       run:
#         working-directory: ./editor
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v4

#       - name: Setup node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20.12"
#           cache: pnpm
#           cache-dependency-path: ./editor/pnpm-lock.yaml

#       - name: Setup pnpm
#         uses: pnpm/action-setup@v4
#         with:
#           version: 8.11.0

#       - name: Install dependencies
#         run: pnpm install

#       - name: Pass formatting
#         run: pnpm run fmt:write

#       - name: Build app
#         run: pnpm run build

#       - name: Install production dependencies
#         run: pnpm install --prod

#       - name: Prepare build assets
#         run: |
#             mkdir -p app/
#             cp -r .next/standalone/* app/
#             mkdir -p app/.next/static
#             cp -r .next/static/* app/.next/static/
#             cp -r public/* app/public/

#       - name: Publish to Cloudflare Pages
#         uses: cloudflare/pages-action@v1
#         with:
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           accountId: YOUR_ACCOUNT_ID
#           projectName: YOUR_PROJECT_NAME
#           directory: ./editor/app
#           # Optional: Enable this if you want to have GitHub Deployments triggered
#           gitHubToken: ${{ secrets.GHCR_TOKEN }}
#           # Optional: Change the working directory
#           workingDirectory: ./editor
#           # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
#           wranglerVersion: "3"
